services:
  client:
    build: .
    environment:
      - MCP_HOST=http://gateway:9011/mcp
    depends_on:
      - gateway

  gateway:
    image: docker/mcp-gateway
    command:
      - --transport=streaming
      - --servers=duckduckgo
      - --verbose=false
      - --port=9011
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
