services:
  gateway:
    image: docker/mcp-gateway:dind
    privileged: true
    ports:
      - "8080:8080"
    command:
      - --port=8080
      - --transport=sse
      - --servers=fetch
      - --memory=512Mb
