services:
  gateway:
    image: docker/mcp-gateway
    volumes:
      - ./catalog.yaml:/mcp/catalog.yaml
    command:
      - --catalog=/mcp/catalog.yaml
      - --servers=gitmcpmoby
      - --transport=sse