name: CI

permissions:
  contents: read

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: ["linux", "darwin", "windows"]

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Lint
        run: make lint-${{ matrix.platform }}

      - name: Tests
        if: matrix.platform == 'linux'
        run: make test

      - name: Build
        run: make docker-mcp-${{ matrix.platform }}
